color_scheme: "dark"
search_enabled: true
title: Pen Testing Knowledge Repo
description: >-
  This is a knowledge repository I've used while learning pentesting techniques. Do not use this information for malicious purposes.
remote_theme: pmarsceill/just-the-docs
github_username:  jhibbard86
aux_links:
  "Justin Hibbard on Github":
    - "//github.com/jhibbard86/PenTestFramework"
